# -*- coding: utf-8 -*-
"""API Maker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FukOUPPqp_D_RalzrsCtkPS8-MFxAY_j
"""

import pickle
from flask import Flask, request, redirect, url_for, flash, jsonify
import numpy as np
import pickle as p
import json

pickle.dump(h5file, open('models/final_prediction.pickle', 'wb'))

app = Flask(__name__)

@app.route('/api/', methods=['POST'])
def makecalc():
    data = request.get_json()
    prediction = np.array2string(model.predict(data))

    return jsonify(prediction)

modelfile = 'models/final_prediction.pickle'
model = p.load(open(modelfile, 'rb'))
app.run(debug=True, host='0.0.0.0') #gcp endpoint
