# -*- coding: utf-8 -*-
"""VideoSplitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZ0GedIuIKeVDz1KdEsJ0VUpqCuHybgv
"""

!pip install moviepy

from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_audio
from moviepy.video.io.VideoFileClip import VideoFileClip
import datetime

CLIP_DURATION = 10 #in minutes
VIDEO_NAME = "video_comp3.mp4"

VFC = VideoFileClip(VIDEO_NAME)

DURATION = VFC.duration

print("Duration: ",VFC.duration)

# file_names=[]
i=1
for time in range (0,int(DURATION),(CLIP_DURATION*60)):
  timestamp=str(datetime.timedelta(seconds = int (time)))
  # targetname="clip-"+timestamp
  targetname="clip-"+str(i)
  i+=1
  ffmpeg_extract_subclip(VIDEO_NAME, time, time+(CLIP_DURATION*60), targetname="video_clips/"+targetname+".mp4")
  try:
    ffmpeg_extract_audio(("video_clips/"+targetname+".mp4"),str("audio_clips/"+targetname+".wav"),bitrate=500)
  except IOError:
    print("No audio source found in video")

i=1
for time in range (0,int(DURATION),2):
  print("Image: img-"+str(i)+".jpg")
  i+=1
  VFC.save_frame("img_frames/img-"+str(i)+".jpg",t=time,withmask=False)